### ISSUE TITLE
Div operation

### ISSUE THREAD

**Issue by DavidZHCN** [eth-sri/psi#2]
I am learning psi. I found a small problem. 
Assume two DExprs a and b have the same guard, such as [x>0]. if we do the div operation a/b and simplify the distribution, the guard will be eliminated. I think it is not right.

**Comment by tgehr** [comment]
Thanks for your report! However, the behaviour is expected. (Which is maybe hard to know, as the expression simplifier so far has no documentation.) Division by zero is undefined, unless it it is guarded by a condition that ensures that no division by zero occurs. If you instead create the expression ``[b≠0]·a/b``, simplification should give you the expected result. In general, if not all values are in the domain of a certain operation, an expression containing the operation needs to be guarded by a condition. You can have a look at ``symbolic.d`` to see how this is done.

This is why, if we do the operation from the source language, the result is correct:

```
$ cat test.psi
def main(x){
	a := x>0;
	b := x>0;
	return a/b;
}
```
```
$ psi test.psi
p(r|x) = [-x≤0]·[x≠0]·δ(1)[r]
Pr[error|x] = [x≤0]
```

**Comment by DavidZHCN** [comment]
That's true. I have missed this. Thanks a lot.
