### ISSUE TITLE
example.psi is expecting prelude.psi

### ISSUE THREAD

**Issue by wchresta** [eth-sri/psi#3]
The example given in the README is expecting prelude.psi to be available.
I expect prelude.psi to be packed with the binary or being available in shared for psi to find prelude. This needs to be documented as it is not obivious.

```
$ cat example.psi 
def main(){
    a := gauss(0,1);
    b := gauss(0,1);
    return if a > b { a } else { b };
}
$ ~/bin/psi example.psi 
error: prelude.psi: no such file
```

**Comment by tgehr** [comment]
Currently, PSI will attempt to read a "library" folder at the location of the binary. You can edit line 10 of psi.d prior to building to customize the default import path. I'll add a note to the README.

**Comment by tgehr** [comment]
I have placed a copy of `prelude.psi` and `prelude-nocheck.psi` into the PSI binary itself. Therefore, your use case will now work without further setup. Thanks for your feedback!

**Comment by wchresta** [comment]
> I have placed a copy of prelude.psi and prelude-nocheck.psi into the PSI binary itself. 

Amazing :) Thanks!

--
Trying to build the newest version gives:

```
$ bash build.sh 
parser.d(536): Error: basic type expected, not foreach
parser.d(536): Error: no identifier for declarator _error_
```

What am I doing wrong?

**Comment by tgehr** [comment]
You are using an old version of the D compiler.
The currently supported version is 2.078.0, though 2.079.0 also works.
Try running `./dependencies.sh`. (If you already did that a while ago, delete the dmd2 directory first.)
