### ISSUE TITLE
util.d causing package collision with pyd

### ISSUE THREAD

**Issue by pedrozudo** [eth-sri/psi#6]
The python package pyd, which allows for interoperability between D-Lang and python does also have a module named util. This causes pyd to complain about psi having likewise a file named util.

Renaming util to dutil (or anything else) resolves this issues and does not require any more to run a renaming script prior to writing a wrapper for psi in python using pyd.

**Comment by tgehr** [comment]
It seems the `pyd` package has since been moved to `pyd.util`.
